name: paper_3d
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  vector_math: any
  provider: ^6.0.5
  flutter_stream_listener: ^2.0.0
  state_machine_animation: ^1.0.2
  uuid: 3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
